/**
 * Generate guidelines data module from markdown files in schema/guidelines/.
 *
 * Produces a TypeScript file with:
 * - guidelinesList: array of { name, title } for listing
 * - guidelinesContent: Record<name, text> for lookup
 * - resolveGuideline(): runtime lookup function
 */
import { readdirSync, readFileSync } from "fs";
import { join } from "path";

const GUIDELINES_DIR = join(__dirname, "..", "guidelines");

interface Guideline {
  name: string;   // slug: "responsive-designs"
  title: string;  // extracted from first heading
  text: string;   // full markdown content
}

function loadGuidelines(): Guideline[] {
  const guidelines: Guideline[] = [];
  let files: string[];
  try {
    files = readdirSync(GUIDELINES_DIR).filter(f => f.endsWith(".md")).sort();
  } catch {
    return guidelines;
  }
  for (const file of files) {
    const name = file.replace(/\.md$/, "");
    const raw = readFileSync(join(GUIDELINES_DIR, file), "utf-8").trim();
    // Extract title from first markdown heading
    const titleMatch = raw.match(/^#+\s+(.+)/m);
    const title = titleMatch ? titleMatch[1].trim() : name.replace(/-/g, " ");
    guidelines.push({ name, title, text: raw });
  }
  return guidelines;
}

export function generateGuidelinesTs(): string {
  const guidelines = loadGuidelines();

  const listEntries = guidelines.map(g => ({ name: g.name, title: g.title }));
  const contentMap: Record<string, string> = {};
  for (const g of guidelines) {
    contentMap[g.name] = g.text;
  }

  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by schema compiler — do not edit`);
  lines.push(``);
  lines.push(`const guidelinesList: { name: string; title: string }[] = ${JSON.stringify(listEntries, null, 2)};`);
  lines.push(``);
  lines.push(`const guidelinesContent: Record<string, string> = ${JSON.stringify(contentMap, null, 2)};`);
  lines.push(``);
  lines.push(`/** Resolve a guidelines query. */`);
  lines.push(`export function resolveGuideline(topic?: string): string {`);
  lines.push(`  if (!topic) {`);
  lines.push(`    const dir = ["# Design Guidelines", ""];`);
  lines.push(`    for (const g of guidelinesList) {`);
  lines.push(`      dir.push("  " + g.name.padEnd(30) + g.title);`);
  lines.push(`    }`);
  lines.push(`    dir.push("");`);
  lines.push(`    dir.push('Use guidelines(topic: "<name>") for full guideline text.');`);
  lines.push(`    return dir.join("\\n");`);
  lines.push(`  }`);
  lines.push(`  const content = guidelinesContent[topic];`);
  lines.push(`  if (content) return content;`);
  lines.push(`  const names = guidelinesList.map(g => g.name);`);
  lines.push(`  return "Unknown guideline: " + topic + ". Available: " + names.join(", ");`);
  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}
