/**
 * Generate prompt registration code and docs from schema/prompts.yaml.
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_DIR = join(__dirname, "..");

interface RawPrompt {
  name: string;
  description: string;
  text: string;
}

function loadPrompts(): RawPrompt[] {
  const raw = readFileSync(join(SCHEMA_DIR, "prompts.yaml"), "utf-8");
  return parseYaml(raw) as RawPrompt[];
}

// ─── Runtime TS generation ──────────────────────────────────────

export function generatePromptsTs(outDir: string): string {
  const prompts = loadPrompts();

  const lines: string[] = [
    `// AUTO-GENERATED by schema compiler — do not edit`,
    `import type { McpServer } from "./types";`,
    ``,
    `export function registerPrompts(server: McpServer) {`,
  ];

  for (const prompt of prompts) {
    lines.push(`  server.registerPrompt(`);
    lines.push(`    ${JSON.stringify(prompt.name)},`);
    lines.push(`    { description: ${JSON.stringify(prompt.description)} },`);
    lines.push(`    () => ({`);
    lines.push(`      messages: [{`);
    lines.push(`        role: "assistant" as const,`);
    lines.push(`        content: {`);
    lines.push(`          type: "text" as const,`);
    lines.push(`          text: ${JSON.stringify(prompt.text.trim())},`);
    lines.push(`        },`);
    lines.push(`      }],`);
    lines.push(`      description: ${JSON.stringify(prompt.description)},`);
    lines.push(`    })`);
    lines.push(`  );`);
    lines.push(``);
  }

  lines.push(`}`);

  const code = lines.join("\n") + "\n";
  const outPath = join(outDir, "prompts.ts");
  writeFileSync(outPath, code);
  console.log(`  Written: ${outPath}`);
  return code;
}

// ─── Docs MDX generation ────────────────────────────────────────

/** Extract a short summary from the prompt text (first paragraph or first N lines) */
function extractSummary(text: string): string[] {
  const lines: string[] = [];
  for (const line of text.trim().split("\n")) {
    // Stop at first code block or heading after initial content
    if (lines.length > 0 && (line.startsWith("```") || line.startsWith("## "))) break;
    lines.push(line);
  }
  return lines;
}

export function generatePromptsDocs(docsRoot: string) {
  const prompts = loadPrompts();

  // English
  const enLines: string[] = [
    "---",
    "title: Prompts",
    "description: Built-in MCP prompts for design strategy and workflows",
    "---",
    "",
    `Vibma includes ${prompts.length} built-in MCP prompts that provide best-practice guidance to AI agents.`,
    "",
  ];

  for (const prompt of prompts) {
    enLines.push(`## ${prompt.name}`);
    enLines.push("");
    enLines.push(prompt.description);
    enLines.push("");
    // Show the full text in a collapsible details block
    enLines.push("<details>");
    enLines.push("<summary>Full prompt text</summary>");
    enLines.push("");
    enLines.push("````md");
    enLines.push(prompt.text.trim());
    enLines.push("````");
    enLines.push("");
    enLines.push("</details>");
    enLines.push("");
  }

  const enPath = join(docsRoot, "src", "content", "docs", "prompts.mdx");
  writeFileSync(enPath, enLines.join("\n"));

  // zh-cn
  const zhDir = join(docsRoot, "src", "content", "docs", "zh-cn");
  mkdirSync(zhDir, { recursive: true });

  const zhLines: string[] = [
    "---",
    "title: Prompts",
    "description: Built-in MCP prompts for design strategy and workflows",
    "---",
    "",
    `Vibma includes ${prompts.length} built-in MCP prompts that provide best-practice guidance to AI agents.`,
    "",
  ];

  for (const prompt of prompts) {
    zhLines.push(`## ${prompt.name}`);
    zhLines.push("");
    zhLines.push(prompt.description);
    zhLines.push("");
    zhLines.push("<details>");
    zhLines.push("<summary>Full prompt text</summary>");
    zhLines.push("");
    zhLines.push(prompt.text.trim());
    zhLines.push("");
    zhLines.push("</details>");
    zhLines.push("");
  }

  writeFileSync(join(zhDir, "prompts.mdx"), zhLines.join("\n"));
  console.log(`  Generated prompts docs (en + zh-cn)`);
}
