/**
 * Generate param key sets from resolved YAML schemas.
 *
 * Single source of truth: handlers import these ReadonlySet<string> values
 * instead of hardcoding param names. The compiler walks resolved endpoints
 * (after $ref, $mixin, and $expand resolution) and emits one named export
 * per discriminated create type, per method with item schemas, and per mixin.
 */
import type { ResolvedEndpoint, RawParam } from "./types";

// $expand preset parts — must match expand.ts PRESETS
const EXPAND_PARTS: Record<string, string[]> = {
  corners: ["topLeftRadius", "topRightRadius", "bottomRightRadius", "bottomLeftRadius"],
  padding: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
  stroke: ["strokeTopWeight", "strokeBottomWeight", "strokeLeftWeight", "strokeRightWeight"],
};

/** Get all param key names from raw mixin data, expanding $expand directives. */
function expandedKeys(params: Record<string, any>): string[] {
  const keys: string[] = [];
  for (const [name, param] of Object.entries(params)) {
    const expand = param?.$expand;
    if (expand && EXPAND_PARTS[expand]) {
      keys.push(name, ...EXPAND_PARTS[expand]);
    } else {
      keys.push(name);
    }
  }
  return keys.sort();
}

/** Convert "frames.create.auto_layout" → "framesCreateAutoLayout" */
function toCamelCase(dottedPath: string): string {
  return dottedPath
    .split(/[._]/)
    .map((seg, i) => (i === 0 ? seg : seg.charAt(0).toUpperCase() + seg.slice(1)))
    .join("");
}

/** Format a Set constructor as readable multi-line when > 6 keys */
function formatSet(keys: string[]): string {
  if (keys.length <= 6) {
    return `new Set(${JSON.stringify(keys)})`;
  }
  const inner = keys.map(k => `  ${JSON.stringify(k)},`).join("\n");
  return `new Set([\n${inner}\n])`;
}

export function generateGuards(
  endpoints: ResolvedEndpoint[],
  mixins: Record<string, Record<string, RawParam>>,
): string {
  const lines: string[] = [
    `// AUTO-GENERATED by schema compiler — do not edit`,
    ``,
  ];

  const seen = new Set<string>();
  const exports: Array<{ name: string; keys: string[]; comment: string }> = [];

  for (const ep of endpoints) {
    for (const method of ep.methods) {
      // Discriminated creates → per-type key sets
      if (method.discriminant && method.types && !method.inherited) {
        for (const [typeName, variant] of Object.entries(method.types)) {
          const path = `${ep.name}.${method.name}.${typeName}`;
          const name = toCamelCase(path);
          if (seen.has(name)) continue;
          seen.add(name);
          const keys = Object.keys(variant.params).sort();
          exports.push({ name, keys, comment: `${ep.name} ${method.name} type="${typeName}"` });
        }
        continue;
      }

      // Methods with item-level schemas
      const itemsParam = method.params?.items;
      if (
        itemsParam?.items &&
        typeof itemsParam.items === "object" &&
        "properties" in itemsParam.items &&
        itemsParam.items.properties &&
        Object.keys(itemsParam.items.properties).length > 0
      ) {
        // Use "node.{method}" for inherited methods (deduplicated), else "{endpoint}.{method}"
        const path = method.inherited ? `node.${method.name}` : `${ep.name}.${method.name}`;
        const name = toCamelCase(path);
        if (seen.has(name)) continue;
        seen.add(name);
        const keys = Object.keys(itemsParam.items.properties).sort();
        exports.push({ name, keys, comment: `${path} item params` });
      }
    }
  }

  // Emit method/type exports
  for (const { name, keys, comment } of exports) {
    lines.push(`/** ${comment} */`);
    lines.push(`export const ${name} = ${formatSet(keys)} as ReadonlySet<string>;`);
    lines.push(``);
  }

  // ─── Mixin key groups ───────────────────────────────────────────
  lines.push(`// ─── Mixin key groups ───────────────────────────────────────────`);
  lines.push(``);

  for (const mixinName of Object.keys(mixins).sort()) {
    const params = mixins[mixinName];
    const keys = expandedKeys(params);
    // "geometry_params" → "mixinGeometryParams"
    const segments = mixinName.split("_");
    const name = "mixin" + segments.map(s => s.charAt(0).toUpperCase() + s.slice(1)).join("");
    lines.push(`/** ${mixinName} */`);
    lines.push(`export const ${name} = ${formatSet(keys)} as ReadonlySet<string>;`);
    lines.push(``);
  }

  return lines.join("\n");
}
