// AUTO-GENERATED response type schemas for docs
// TODO: Phase 2 — generate from YAML response definitions
// For now, this is a placeholder that the full migration will fill in.

import type { ResolvedEndpoint } from "./types";

export function generateResponseTypes(endpoints: ResolvedEndpoint[]): string {
  const lines: string[] = [
    `// AUTO-GENERATED by schema compiler — do not edit`,
    ``,
    `/** Runtime JSON Schema + example for each endpoint's response, per method. */`,
    `export const generatedResponseSchemas: Record<string, Record<string, unknown>> = {`,
  ];

  for (const ep of endpoints) {
    lines.push(`  "${ep.name}": {`);
    for (const method of ep.methods) {
      if (method.response.example) {
        lines.push(`    "${method.name}": ${JSON.stringify({ example: method.response.example })},`);
      }
    }
    lines.push(`  },`);
  }

  lines.push(`};`);
  return lines.join("\n") + "\n";
}
